name = input ("What is your name?")
age = input ("What is your age?")
print (f"Hello {name}, you are {age} years old")
food = input ("What's your favourite food?")
birth_year = int(input("What year were you born?"))
print (f"In 2050, you'll be {2050 - birth_year} years old and hopefully eating lots of {food}.")